import * as dotenv from 'dotenv';

dotenv.config();
const CONFIG_ENV = process.env;

export const GENERAL_CONFIG = {
  SERVER_URL: CONFIG_ENV.SERVER_URL,
};

export const DATABASE_CONFIG_POSTGRESQL = {
  TYPE: CONFIG_ENV.DB_TYPE_POSTGRESQL || 'postgres',
  HOST: CONFIG_ENV.DB_HOST_POSTGRESQL,
  USERNAME: CONFIG_ENV.DB_USERNAME_POSTGRESQL,
  PASSWORD: CONFIG_ENV.DB_PASSWORD_POSTGRESQL,
  DATABASE: CONFIG_ENV.DB_NAME_POSTGRESQL,
  PORT: +CONFIG_ENV.DB_PORT_POSTGRESQL || 5432,
  LOGGING: CONFIG_ENV.DB_LOGGING == 'ENABLED',
};

export const SWAGGER_CONFIG = {
  URL: CONFIG_ENV.SWAGGER_URL,
};

export const LOG_CONFIG = {
  CONSOLE_SILENT: CONFIG_ENV.LOGGER_CONSOLE_SILENT,
  MAX_SIZE_SILENT: CONFIG_ENV.LOGGER_MAX_SIZE_SILENT,
  MAX_SIZE_PATH: CONFIG_ENV.LOGGER_MAX_SIZE_PATH,
  DAILY_SILENT: CONFIG_ENV.LOGGER_DAILY_SILENT,
  DAILY_PATH: CONFIG_ENV.LOGGER_DAILY_PATH,
  DAILY_PATTERN: CONFIG_ENV.LOGGER_DAILY_PATTERN,
};

export const CORS_CONFIG = {
  ALLOWED_URL: CONFIG_ENV.CORS_ALLOWED_URL,
};
